# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/weifish/Desktop/I2P-I-2024_FinalProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/weifish/Desktop/I2P-I-2024_FinalProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/weifish/Desktop/I2P-I-2024_FinalProject/CMakeFiles /Users/weifish/Desktop/I2P-I-2024_FinalProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/weifish/Desktop/I2P-I-2024_FinalProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

Final_Codes/UI.o: Final_Codes/UI.c.o
.PHONY : Final_Codes/UI.o

# target to build an object file
Final_Codes/UI.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/UI.c.o
.PHONY : Final_Codes/UI.c.o

Final_Codes/UI.i: Final_Codes/UI.c.i
.PHONY : Final_Codes/UI.i

# target to preprocess a source file
Final_Codes/UI.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/UI.c.i
.PHONY : Final_Codes/UI.c.i

Final_Codes/UI.s: Final_Codes/UI.c.s
.PHONY : Final_Codes/UI.s

# target to generate assembly for a file
Final_Codes/UI.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/UI.c.s
.PHONY : Final_Codes/UI.c.s

Final_Codes/bullet.o: Final_Codes/bullet.c.o
.PHONY : Final_Codes/bullet.o

# target to build an object file
Final_Codes/bullet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/bullet.c.o
.PHONY : Final_Codes/bullet.c.o

Final_Codes/bullet.i: Final_Codes/bullet.c.i
.PHONY : Final_Codes/bullet.i

# target to preprocess a source file
Final_Codes/bullet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/bullet.c.i
.PHONY : Final_Codes/bullet.c.i

Final_Codes/bullet.s: Final_Codes/bullet.c.s
.PHONY : Final_Codes/bullet.s

# target to generate assembly for a file
Final_Codes/bullet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/bullet.c.s
.PHONY : Final_Codes/bullet.c.s

Final_Codes/enemy.o: Final_Codes/enemy.c.o
.PHONY : Final_Codes/enemy.o

# target to build an object file
Final_Codes/enemy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/enemy.c.o
.PHONY : Final_Codes/enemy.c.o

Final_Codes/enemy.i: Final_Codes/enemy.c.i
.PHONY : Final_Codes/enemy.i

# target to preprocess a source file
Final_Codes/enemy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/enemy.c.i
.PHONY : Final_Codes/enemy.c.i

Final_Codes/enemy.s: Final_Codes/enemy.c.s
.PHONY : Final_Codes/enemy.s

# target to generate assembly for a file
Final_Codes/enemy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/enemy.c.s
.PHONY : Final_Codes/enemy.c.s

Final_Codes/game.o: Final_Codes/game.c.o
.PHONY : Final_Codes/game.o

# target to build an object file
Final_Codes/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/game.c.o
.PHONY : Final_Codes/game.c.o

Final_Codes/game.i: Final_Codes/game.c.i
.PHONY : Final_Codes/game.i

# target to preprocess a source file
Final_Codes/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/game.c.i
.PHONY : Final_Codes/game.c.i

Final_Codes/game.s: Final_Codes/game.c.s
.PHONY : Final_Codes/game.s

# target to generate assembly for a file
Final_Codes/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/game.c.s
.PHONY : Final_Codes/game.c.s

Final_Codes/game_scene.o: Final_Codes/game_scene.c.o
.PHONY : Final_Codes/game_scene.o

# target to build an object file
Final_Codes/game_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/game_scene.c.o
.PHONY : Final_Codes/game_scene.c.o

Final_Codes/game_scene.i: Final_Codes/game_scene.c.i
.PHONY : Final_Codes/game_scene.i

# target to preprocess a source file
Final_Codes/game_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/game_scene.c.i
.PHONY : Final_Codes/game_scene.c.i

Final_Codes/game_scene.s: Final_Codes/game_scene.c.s
.PHONY : Final_Codes/game_scene.s

# target to generate assembly for a file
Final_Codes/game_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/game_scene.c.s
.PHONY : Final_Codes/game_scene.c.s

Final_Codes/loading_scene.o: Final_Codes/loading_scene.c.o
.PHONY : Final_Codes/loading_scene.o

# target to build an object file
Final_Codes/loading_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/loading_scene.c.o
.PHONY : Final_Codes/loading_scene.c.o

Final_Codes/loading_scene.i: Final_Codes/loading_scene.c.i
.PHONY : Final_Codes/loading_scene.i

# target to preprocess a source file
Final_Codes/loading_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/loading_scene.c.i
.PHONY : Final_Codes/loading_scene.c.i

Final_Codes/loading_scene.s: Final_Codes/loading_scene.c.s
.PHONY : Final_Codes/loading_scene.s

# target to generate assembly for a file
Final_Codes/loading_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/loading_scene.c.s
.PHONY : Final_Codes/loading_scene.c.s

Final_Codes/main.o: Final_Codes/main.c.o
.PHONY : Final_Codes/main.o

# target to build an object file
Final_Codes/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/main.c.o
.PHONY : Final_Codes/main.c.o

Final_Codes/main.i: Final_Codes/main.c.i
.PHONY : Final_Codes/main.i

# target to preprocess a source file
Final_Codes/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/main.c.i
.PHONY : Final_Codes/main.c.i

Final_Codes/main.s: Final_Codes/main.c.s
.PHONY : Final_Codes/main.s

# target to generate assembly for a file
Final_Codes/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/main.c.s
.PHONY : Final_Codes/main.c.s

Final_Codes/map.o: Final_Codes/map.c.o
.PHONY : Final_Codes/map.o

# target to build an object file
Final_Codes/map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/map.c.o
.PHONY : Final_Codes/map.c.o

Final_Codes/map.i: Final_Codes/map.c.i
.PHONY : Final_Codes/map.i

# target to preprocess a source file
Final_Codes/map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/map.c.i
.PHONY : Final_Codes/map.c.i

Final_Codes/map.s: Final_Codes/map.c.s
.PHONY : Final_Codes/map.s

# target to generate assembly for a file
Final_Codes/map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/map.c.s
.PHONY : Final_Codes/map.c.s

Final_Codes/menu_scene.o: Final_Codes/menu_scene.c.o
.PHONY : Final_Codes/menu_scene.o

# target to build an object file
Final_Codes/menu_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/menu_scene.c.o
.PHONY : Final_Codes/menu_scene.c.o

Final_Codes/menu_scene.i: Final_Codes/menu_scene.c.i
.PHONY : Final_Codes/menu_scene.i

# target to preprocess a source file
Final_Codes/menu_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/menu_scene.c.i
.PHONY : Final_Codes/menu_scene.c.i

Final_Codes/menu_scene.s: Final_Codes/menu_scene.c.s
.PHONY : Final_Codes/menu_scene.s

# target to generate assembly for a file
Final_Codes/menu_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/menu_scene.c.s
.PHONY : Final_Codes/menu_scene.c.s

Final_Codes/player.o: Final_Codes/player.c.o
.PHONY : Final_Codes/player.o

# target to build an object file
Final_Codes/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/player.c.o
.PHONY : Final_Codes/player.c.o

Final_Codes/player.i: Final_Codes/player.c.i
.PHONY : Final_Codes/player.i

# target to preprocess a source file
Final_Codes/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/player.c.i
.PHONY : Final_Codes/player.c.i

Final_Codes/player.s: Final_Codes/player.c.s
.PHONY : Final_Codes/player.s

# target to generate assembly for a file
Final_Codes/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/player.c.s
.PHONY : Final_Codes/player.c.s

Final_Codes/setting_scene.o: Final_Codes/setting_scene.c.o
.PHONY : Final_Codes/setting_scene.o

# target to build an object file
Final_Codes/setting_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/setting_scene.c.o
.PHONY : Final_Codes/setting_scene.c.o

Final_Codes/setting_scene.i: Final_Codes/setting_scene.c.i
.PHONY : Final_Codes/setting_scene.i

# target to preprocess a source file
Final_Codes/setting_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/setting_scene.c.i
.PHONY : Final_Codes/setting_scene.c.i

Final_Codes/setting_scene.s: Final_Codes/setting_scene.c.s
.PHONY : Final_Codes/setting_scene.s

# target to generate assembly for a file
Final_Codes/setting_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/setting_scene.c.s
.PHONY : Final_Codes/setting_scene.c.s

Final_Codes/utility.o: Final_Codes/utility.c.o
.PHONY : Final_Codes/utility.o

# target to build an object file
Final_Codes/utility.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/utility.c.o
.PHONY : Final_Codes/utility.c.o

Final_Codes/utility.i: Final_Codes/utility.c.i
.PHONY : Final_Codes/utility.i

# target to preprocess a source file
Final_Codes/utility.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/utility.c.i
.PHONY : Final_Codes/utility.c.i

Final_Codes/utility.s: Final_Codes/utility.c.s
.PHONY : Final_Codes/utility.s

# target to generate assembly for a file
Final_Codes/utility.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/utility.c.s
.PHONY : Final_Codes/utility.c.s

Final_Codes/weapon.o: Final_Codes/weapon.c.o
.PHONY : Final_Codes/weapon.o

# target to build an object file
Final_Codes/weapon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/weapon.c.o
.PHONY : Final_Codes/weapon.c.o

Final_Codes/weapon.i: Final_Codes/weapon.c.i
.PHONY : Final_Codes/weapon.i

# target to preprocess a source file
Final_Codes/weapon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/weapon.c.i
.PHONY : Final_Codes/weapon.c.i

Final_Codes/weapon.s: Final_Codes/weapon.c.s
.PHONY : Final_Codes/weapon.s

# target to generate assembly for a file
Final_Codes/weapon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Final_Codes/weapon.c.s
.PHONY : Final_Codes/weapon.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Game"
	@echo "... Final_Codes/UI.o"
	@echo "... Final_Codes/UI.i"
	@echo "... Final_Codes/UI.s"
	@echo "... Final_Codes/bullet.o"
	@echo "... Final_Codes/bullet.i"
	@echo "... Final_Codes/bullet.s"
	@echo "... Final_Codes/enemy.o"
	@echo "... Final_Codes/enemy.i"
	@echo "... Final_Codes/enemy.s"
	@echo "... Final_Codes/game.o"
	@echo "... Final_Codes/game.i"
	@echo "... Final_Codes/game.s"
	@echo "... Final_Codes/game_scene.o"
	@echo "... Final_Codes/game_scene.i"
	@echo "... Final_Codes/game_scene.s"
	@echo "... Final_Codes/loading_scene.o"
	@echo "... Final_Codes/loading_scene.i"
	@echo "... Final_Codes/loading_scene.s"
	@echo "... Final_Codes/main.o"
	@echo "... Final_Codes/main.i"
	@echo "... Final_Codes/main.s"
	@echo "... Final_Codes/map.o"
	@echo "... Final_Codes/map.i"
	@echo "... Final_Codes/map.s"
	@echo "... Final_Codes/menu_scene.o"
	@echo "... Final_Codes/menu_scene.i"
	@echo "... Final_Codes/menu_scene.s"
	@echo "... Final_Codes/player.o"
	@echo "... Final_Codes/player.i"
	@echo "... Final_Codes/player.s"
	@echo "... Final_Codes/setting_scene.o"
	@echo "... Final_Codes/setting_scene.i"
	@echo "... Final_Codes/setting_scene.s"
	@echo "... Final_Codes/utility.o"
	@echo "... Final_Codes/utility.i"
	@echo "... Final_Codes/utility.s"
	@echo "... Final_Codes/weapon.o"
	@echo "... Final_Codes/weapon.i"
	@echo "... Final_Codes/weapon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

